### ISSUE TITLE
No audio autoplay in reviews

### ISSUE THREAD

**Issue by squasheds** [xiprox/WaniKani-for-Android#38]
It works when doing lessons but when doing reviews, I always have to press the little speaker to get the audio =/. It's not really that big a deal but it would be a nice fix to make it even better :D.

**Comment by xiprox** [comment]
This is known. Was going to create an issue myself. I'm hoping to get this fixed soon.

**Comment by xiprox** [comment]
Ok. I managed to reproduce this. However, it looks like this is something to do with wanikani.com and not the app as the same behavior seems to exist in Chrome for Android too. 

Anyone can confirm?

**Comment by squasheds** [comment]
I can confirm it's not related to wk.com itself, I just tried it in Chrome (55.0.2883.87 m) and in Opera (42.0.2393.94) running on Win7 Home Premium and in both cases audio autoplays in the reviews. In both Chrome and Opera I have no scripts to modify WK behavior. I otherwise always use it in Firefox with a couple of scripts (none audio-related) and have no problem with audio autoplay.

**Comment by squasheds** [comment]
Confirmed, on two different phones. It works ok with Firefox though.

**Comment by jneapan** [comment]
This should be fixed in the latest commit. Android's WebView usually has automatic media playback off by default, enabling that flag fixes the issue.

**Comment by squasheds** [comment]
Unless this latest commit has yet to come out, I think it wasnt fixed. Im still experiencing the same issue.

Or is this "webview media playback flag" something I can enable in my device?

**Comment by jneapan** [comment]
You'll have to wait until the next version comes out. AFAIK you can't enable it from outside the app.

**Comment by bountin** [comment]
@xiprox Any chance for a release soon? I've managed to build the project myself and the fix is awesome but I'd still like to be back on the store version again, so that I don't miss further updates.

**Comment by madmalkav** [comment]
Pleaae release patched version in the store.

**Comment by xiprox** [comment]
I just pushed this change (along with others) to the alpha channel on the Play Store. Feel free to check it out. Info on alpha testing: https://github.com/xiprox/WaniKani-for-Android#alpha-testing

cc @bountin @madmalkav

**Comment by madmalkav** [comment]
Thanks for the info. When I try to subscribe to the alpha, the link tells me my account isn't qualified.

**Comment by xiprox** [comment]
Looks like the config on the Play Console had an issue. Fixed and should be working now.

**Comment by squasheds** [comment]
works now!

**Comment by bountin** [comment]
Great, thank you very much @xiprox !

**Comment by maxb** [comment]
It's splendid that there's a fix for this - I just found this issue and switched to the alpha channel.

Don't forget to push it out to the stable channel too! :-)
